spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/farm
    username: root
    password: 
  jpa:
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL5Dialect